resolver: lts-22.22
packages:
- tpa

ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef

extra-deps:
- github: NorfairKing/safe-coloured-text
  commit: 61f14d21b7399fe97da24e484c2f9fedaf532bb8
  subdirs:
  - safe-coloured-text
  - safe-coloured-text-layout
  - safe-coloured-text-gen
- github: NorfairKing/autodocodec
  commit: a818df53b0f65caf3615d5cb9d4734288ff1ca39
  subdirs:
    - autodocodec
    - autodocodec-yaml
    - autodocodec-schema
- github: NorfairKing/opt-env-conf
  commit: 0f3d914b16551e88c1cc60060121c3da747c0a38
  subdirs:
    - opt-env-conf
    - opt-env-conf-test

system-ghc: true
nix:
  enable: false
with-hpack: hpack
