resolver: lts-24.38
packages:
- tpa
ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef

extra-deps:
- github: NorfairKing/safe-coloured-text
  commit: 5d1187b7873a8a1e397245c7c0c6d9ab88765d67
  subdirs:
  - safe-coloured-text
  - safe-coloured-text-layout
  - safe-coloured-text-gen
- github: NorfairKing/autodocodec
  commit: 29b57dc2d425d732ce75143ecf3fc6411df0347b
  subdirs:
    - autodocodec
    - autodocodec-yaml
    - autodocodec-schema
    - autodocodec-nix
- github: NorfairKing/opt-env-conf
  commit: de7ac850e960c28e5182810515a87fbe1d6daede
  subdirs:
    - opt-env-conf
    - opt-env-conf-test

system-ghc: true
nix:
  enable: false
with-hpack: hpack
