resolver: lts-22.39
packages:
- tpa
ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef

extra-deps:
- github: NorfairKing/safe-coloured-text
  commit: 26b7657428f277f819a0831cbddddb7f4c5408f9
  subdirs:
  - safe-coloured-text
  - safe-coloured-text-layout
  - safe-coloured-text-gen
- github: NorfairKing/autodocodec
  commit: b435803c3367b06c0d38acd90a54ba63e63fb6be
  subdirs:
    - autodocodec
    - autodocodec-yaml
    - autodocodec-schema
    - autodocodec-nix
- github: NorfairKing/opt-env-conf
  commit: ecfcf2a41edad94fd2b7c1d0bdd8654fbcb1545c
  subdirs:
    - opt-env-conf
    - opt-env-conf-test

system-ghc: true
nix:
  enable: false
with-hpack: hpack
