# DO NOT EDIT THIS FILE DIRECTLY
# This file was generated by
# tpa:test/Tpa/OptParseSpec.hs:13
# To update this it, run the test with --golden-reset
{ lib }:
{
  key-paths = lib.mkOption {
    default = null;
    description = "key paths";
    type = lib.types.nullOr (lib.types.listOf lib.types.str);
  };
}
