name:                tpa
version:             0.0.0.0
github:              "NorfairKing/tpa"
license:             AllRightsReserved
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright (c) 2021 Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - autodocodec
  - autodocodec-yaml
  - base32
  - bytestring
  - cryptonite
  - directory
  - filepath
  - optparse-applicative
  - path
  - path-io
  - text
  - time

executables:
  tpa:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tpa
